<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html dir="ltr" lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <title>DEMO SHOP</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta http-equiv="Content-Language" content="ru,en">
    <meta name="distribution" content="GLOBAL">
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl('bootstrap/css/bootstrap.css'); ?> ">
</head>
<body>
 <div class="navbar">
     <div class="navbar-inner">
         <ul class="nav">
             <li> <a href="<?php echo $this->baseUrl(); ?>/user/index/login" />Авторизация</a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/client/index/list" >Список клиентов</a></li>
             <li><a href=<?php echo $this->url(array('page'=>'order'),'static-content');?> >Сделать заказ</a></li>

         </ul>
     </div>
 </div>
<?php echo $this->layout()->content ?>
</body>
</html>