

<table id="orders" class="table table-striped">
    <thead>
    <tr>
        <td><?php echo $this->translate->translate("sum");?></a></td>
        <td><?php echo $this->translate->translate("date");?></td>
        <td><?php echo $this->translate->translate("client_code");?></td>
        <td><?php echo $this->translate->translate("product");?></td>
        <td><?php echo $this->translate->translate("price");?></td>
    </tr>
    </thead>

    <tbody>
    <?php foreach ($this->list as $key => $value){
        echo "<tr>";
        echo "<td>".$value["sum"]."</td>";
        echo "<td>".$value["date"]."</td>";
        echo "<td>".$value["client_code"]."</td>";
        echo "<td>".$value["product_name"]."</td>";
        echo "<td>".$value["price"]."</td>";
    }   echo "</tr>";
    ?>
    </tbody>

</table>