<img src=<?php echo $this->image?> / >
    <table id="orders" class="table table-striped">
        <thead>
        <tr>
            <td><?php echo $this->translate->translate("first_name");?></td>
            <td><?php echo $this->translate->translate("second_name");?></td>
            <td><?php echo $this->translate->translate("country");?></td>
            <td><?php echo $this->translate->translate("city");?></td>
            <td><?php echo $this->translate->translate("phone");?></td>
            <td><?php echo $this->translate->translate("email");?></td>
            <td><?php echo $this->translate->translate("sum");?></a></td>
            <td><?php echo $this->translate->translate("date");?></td>
            <td><?php echo $this->translate->translate("client_code");?></td>
            <td><?php echo $this->translate->translate("product");?></td>
            <td><?php echo $this->translate->translate("price");?></td>
        </tr>
        </thead>

        <tbody>
        <?php $i = 2;
        foreach ($this->list as $key => $value){

            echo "<tr>";

            echo "<td>".$value["first_name"]."</td>";
            echo "<td>".$value["second_name"]."</td>";
            echo "<td>".$value["country"]."</td>";
            echo "<td>".$value["city"]."</td>";
            echo "<td>".$value["phone"]."</td>";
            echo "<td>".$value["email"]."</td>";
            echo "<td>".$value["sum"]."</td>";
            echo "<td>".$value["date"]."</td>";
            echo "<td>".$value["client_code"]."</td>";
            echo "<td class='product'>".$value["product_name"]."</td>";
            echo "<td>".$value["price"]."</td>";
        }   echo "</tr>";
        ?>
        </tbody>