<table id="clients" class="table table-striped">
    <thead>
    <tr>
        <td><?php echo $this->translate("first_name");?></td>
        <td><?php echo $this->translate("second_name");?></td>
        <td><?php echo $this->translate("country");?></td>
        <td><?php echo $this->translate("city");?></td>
        <td><?php echo $this->translate("phone");?></td>
        <td><?php echo $this->translate("email");?></td>
        </tr>
    </thead>

    <tbody>
    <?php $i = 2;
    foreach ($this->list as $key => $value){

   echo "<tr>";

    echo "<td class=send client_id=".$value["id"].">".$value["first_name"]."</td>";
    echo "<td>".$value["second_name"]."</td>";
    echo "<td>".$value["country"]."</td>";
    echo "<td>".$value["city"]."</td>";
    echo "<td>".$value["phone"]."</td>";
    echo "<td>".$value["email"]."</td>";
}   echo "</tr>";
    ?>
    </tbody>

</table>
    <div id="log" title=<?php echo $this->translate->translate("orders_title"); ?> ></div>
<!-- "<a href=".$this->baseUrl()."/order/index/orderlist/client/".$value["id"].">order list</a>"; -->
<script type="text/javascript" src="/js/four_button.js"></script>
<script type="text/javascript">
    var next =    "<?php echo $this->translate("datatable_next_page");?> ";
    var prev =    "<?php echo $this->translatee("datatable_previus_page");?>";
    var first =    "<?php echo $this->translate("datatable_first_page");?>"
    var last =    "<?php echo $this->translate("datatable_last_page");?>";
    var menu_entries  =    "<?php echo $this->translate("show_menu_entries");?>";
    var search  =     "<?php echo $this->translate("form_search");?>";
    var from_to =     "<?php echo $this->translate("form_start_end");?>";

    $(function( ){

    $('#clients').dataTable({
        "sPaginationType": "four_button",
        "oLanguage": {
            "sLengthMenu": menu_entries ,
            "sSearch": search  ,
            "sInfo" : from_to


        }});
        $(".send").bind("click",show_orders)   ;
    });
    function show_orders(){

        var request = $.ajax({
            url: "/order/index/orderlist/",
            type: "POST",
            data: {client : $(this).attr("client_id") }

        });
        request.done(function(msg) {
            $("#log").html( msg );
            $("#log").dialog({width:1000,height:800});
            $('#orders').dataTable({
                "sPaginationType": "four_button",
                "oLanguage": {
                    "sLengthMenu": menu_entries ,
                    "sSearch": search  ,
                    "sInfo" : from_to  ,
                    "oPaginate": {
                        "sNext": next,
                        "sPrevious": prev
                    }
               }
            });
           // $("#orders_previous").addClass("btn btn-warning");
          //  $("#orders_next").addClass("btn btn-warning");

            });


    }




    </script>