<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html dir="ltr" lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <title>DEMO SHOP</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta http-equiv="Content-Language" content="ru,en">
    <meta name="distribution" content="GLOBAL">
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl('bootstrap/css/bootstrap.css'); ?> ">
    <link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl('jquery-ui/css/ui-lightness/styles.css'); ?> ">
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('js/jquery.dataTables.js'); ?>"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl('jquery-ui/js/jquery-ui.js'); ?>"></script>
</head>
<body>
 <div class="navbar">
     <div class="navbar-inner">
         <ul class="nav">
             <li> <a href="<?php echo $this->baseUrl(); ?>/user/index/login" /><?php echo $this->translate->translate("log_in");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/client/index/list" ><?php echo $this->translate->translate("clients_list");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/order/index/index" ><?php echo $this->translate->translate("add_order");?></a></li>
             <li><a href="<?php echo $this->url(array("module"=>"default",
                                             "controller"=>"locale",
                                              "action"=>"index","locale" => "ru","default",true)); ?>"><img src=<?php echo $this->baseUrl("pictures/ru.png");?> /></a></li>
             <li><a href="<?php echo $this->url(array("module"=>"default",
                 "controller"=>"locale",
                 "action"=>"index","locale" => "en","default",true)); ?>"><img src=<?php echo $this->baseUrl("pictures/en.jpg");?> /></a></li>

         </ul>
     </div>
 </div>
<?php echo $this->layout()->content ?>

</body>
</html>