<?php echo $this->doctype(); ?>
<html dir="ltr" lang="ru" xmlns="http://www.w3.org/1999/html">
<head>
    <title>DEMO SHOP</title>
     <meta http-equiv="Content-Type" content="text/html; charset=utf-8" >
    <meta http-equiv="Content-Language" content="ru,en">
    <meta name="distribution" content="GLOBAL">

    <?php
    $this->headLink()->appendStylesheet('/css/styles.css')
                    ->prependStylesheet('/bootstrap/css/bootstrap.css')
                    ->prependStylesheet('/jquery-ui/css/ui-lightness/styles.css');


    ?>

    <?php echo $this->headLink() ?>
   <?php  $this->headScript()->appendFile(
    '/js/jquery.js',
    'text/javascript'
     );
    $this->headScript()->appendFile(
        '/js/jquery.dataTables.js',
        'text/javascript'
     );
    $this->headScript()->appendFile(
        '/jquery-ui/js/jquery-ui.js',
        'text/javascript'
    );?>
<?php echo $this->headScript();?>
</head>
<body>
 <div class="navbar">
     <div class="navbar-inner">
         <ul class="nav">
             <li> <a href="<?php echo $this->baseUrl(); ?>/user/index/login" /><?php echo $this->translate->translate("log_in");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/client/index/list" ><?php echo $this->translate->translate("clients_list");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/order/index/index" ><?php echo $this->translate->translate("add_order");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/order/index/country" ><?php echo $this->translate->translate("reports_country");?></a></li>
             <li><a href="<?php echo $this->baseUrl(); ?>/order/index/city" ><?php echo $this->translate->translate("reports_city");?></a></li>
             <li><a href="<?php echo $this->url(array("module"=>"default",
                                             "controller"=>"index",
                                              "action"=>"locale","locale" => "ru","default",true)); ?>"><img src=<?php echo $this->baseUrl("pictures/ru.png");?> /></a></li>
             <li><a href="<?php echo $this->url(array("module"=>"default",
                 "controller"=>"index",
                 "action"=>"locale","locale" => "en","default",true)); ?>"><img src=<?php echo $this->baseUrl("pictures/en.jpg");?> /></a></li>

         </ul>
     </div>
 </div>
<?php echo $this->layout()->content ?>

</body>
</html>